name: benchmark

channels:
  - conda-forge 

dependencies:
  - python==3.10
  - pyscipopt
  - coin-or-cbc
  - pyglpk
  - pip
  - pip:
    - reframed
    - pulp
    - highspy
    - cylp
    - glpk
    - gurobipy
